### ISSUE TITLE
How change font?

### ISSUE THREAD

**Issue by Radzhab** [pauledavey/CodeSharper.PowerPoint.Helper#1]
How embed font?

**Comment by pauledavey** [comment]
Hi Radzhab,

Do you mean you want to change the font to a different type within a text box?

You specify the font you want to use by setting the FontName property. A list of font names you can look through can be found here:  https://www.microsoft.com/typography/fonts/family.aspx

As an example, if you look in the source code and look at the Codesharper.PowerPoint.Helper.Tester project, Program.cs file.

If you look at the section of code starting at line 148. This section writes the title text on to the first slide in the demonstration.pptx file.

If you wanted to set the font to 'webdings' here you would simply set the FontName, like this:

Original Code:
// Set the text in the textboxes
            PptShapeManager.SetTextBoxText(textShape1, "CodeSharper PowerPoint Helper");
            textShape1.TextEffect.FontBold = MsoTriState.msoTrue;
            textShape1.TextEffect.FontSize = 42f;

Setting the FontName:
// Set the text in the textboxes
            PptShapeManager.SetTextBoxText(textShape1, "CodeSharper PowerPoint Helper");
            textShape1.TextEffect.FontBold = MsoTriState.msoTrue;
            textShape1.TextEffect.FontSize = 42f;
            textShape1.TextEffect.FontName = "Webdings";

Hope that resolves things for you.

Regards,
Paul
